layout_spectrum: 0.03140799
typography_spectrum: 0.08902542
color:
  saturation: 0.9914541
  lightness: 0.1613725
  brandStrength: 0.714647
  rhythmicContrast: 0.4733433
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Show The Grid
